### ISSUE TITLE
SVG to laser cut

### ISSUE THREAD

**Issue by JartX** [rafaeldelboni/buildlogs#1]
Hi, can you upload the svg? I have searched but i dont found anything :(

**Comment by rafaeldelboni** [comment]
You can find a the crkbd acrylic plate files here:
https://github.com/foostan/crkbd/tree/master/plates

**Comment by JartX** [comment]
> You can find a the crkbd acrylic plate files here:
> https://github.com/foostan/crkbd/tree/master/plates

I saw it, but what are they? there are many options

**Comment by rafaeldelboni** [comment]
So probably you want this one:
https://github.com/foostan/crkbd/blob/master/plates/common/top-bottom.ai
![image](https://user-images.githubusercontent.com/1683898/110997830-b7dee480-835c-11eb-98ae-be8770e97ec2.png)

**Comment by rafaeldelboni** [comment]
@JartX That's what you were looking for? Can I close this issue?

**Comment by JartX** [comment]
> @JartX That's what you were looking for? Can I close this issue?

yes! Many thanks! now waiting the aliexpress components..two years later.. Yes! my components have been arrived! :D

**Comment by rafaeldelboni** [comment]
Oh cool, please send me the pictures of your keyboard after you finish building it.
