### ISSUE TITLE
[Request] help with ordering from JLC

### ISSUE THREAD

**Issue by Niryo** [rafaeldelboni/buildlogs#12]
A complete newbie here, I have uploaded the gerber zip to JLC and I am trying to understand if I need to configure anything (other than choosing a custom color). Should I keep everything as default? if not, can you put here (or in the guide) a screenshot of the JLC page with the correct configurations?

**Comment by Niryo** [comment]
@rafaeldelboni also, another question regarding the pcb- do you have a version of the Gerber files that supports hotswap sockets for the key switches?

**Comment by rafaeldelboni** [comment]
Usually, I just stick with the defaults from JLCPCB, only changing the PCB color. If there's anything wrong with my order, they usually email me to let me know what's up or give any warnings before manufacturing.

For the Gerber files, you can follow this guide:
[PCB Guide](https://github.com/GEIGEIGEIST/TOTEM/tree/main/PCB)

**Comment by Niryo** [comment]
Cool, thanks!

**Comment by rafaeldelboni** [comment]
Sorry, I just assumed you were building the Totem. Which keyboard are you talking about?

The guide I linked works for any project—you just need to upload the right Gerber files.

**Comment by Niryo** [comment]
I am talking about the [crone choc guide](https://github.com/rafaeldelboni/buildlogs/blob/main/crkbd-choc-spaced-switch.md). As I understand, the pcb for this guide is for direct soldering and doesn't support hotswap key sockets, so I am wondering if there is a way to get the exact pcb but with places for the sockets.

**Comment by rafaeldelboni** [comment]
For this exact PCB I don't think there is a variation with hot swaps, what you could do is use the [Original Corne 2.1.0 Choc PCB](https://github.com/foostan/crkbd/releases/tag/corne-chocolate-v2.1.0), but keep in mind this PCB is no made with wireless in mind, so no power switch and battery soldering points.

(Those aren't required, but is a nice to have a way to turn off the keyboard via hardware and you can solder the batt directly in the nice!nanos)

**Comment by Niryo** [comment]
I see, so I think i'll stick with the non-swappable build now. thanks. 
btw, is it your own modified version or did you find it somewhere? (maybe there is wireless swappable version from where it came from unless it's your own modification:))

**Comment by rafaeldelboni** [comment]
It's from here:
https://github.com/davidphilipbarr/Choc-Spaced-Corne/tree/main/chocorne-switch

**Comment by Niryo** [comment]
Great, thanks!
