### ISSUE TITLE
question regarding the diodes 

### ISSUE THREAD

**Issue by Niryo** [rafaeldelboni/buildlogs#13]
I ordered the same diodes as yours in [this](https://github.com/rafaeldelboni/buildlogs/blob/main/crkbd-choc-spaced-switch.md) guide, but i am getting a bit higher om measurements (~670 instead of ~570) on each diode. will it have any impact?
I am trying to debug a faulty key, the `o` key is "stuck" in an infinite loop until I interrupt it with other keys, and my whole top row is a bit funky, for example when I press `y` it sometimes triggers the infinite `o` again. I am trying to understand if it's an issue with the diodes or maybe the pcb itself (it reproduces without the switch so I am sure it's not the `o` switch).

**Comment by rafaeldelboni** [comment]
I bought the following variation: 1N4148W T4 SOD-123 and used in many builds and never had problems, but I confess I never checked the outputs. I thinks small variations are normal and usually this problems are related to soldering like cold joints or solder blobs doing some unwanted contacts.
![Screenshot_20240903_075747_Firefox Nightly](https://github.com/user-attachments/assets/e902bdbf-805b-4c87-97ed-16bbaa8f06e6)

**Comment by Niryo** [comment]
yea I bought the exact same one as yours, and I think too that the issue is in one of the joints, I just wanted to rule out the the diodes. I will try going over all the joints again. thanks!
