### ISSUE TITLE
Extra $4 charge

### ISSUE THREAD

**Issue by MikaelElkiaer** [rafaeldelboni/buildlogs#3]
> After a day I placed the order they sent me an email asking for an extra U$ 4.00, I didn't understand what happened, but I just paid it and everything worked fine.

Same thing happened to me. Apparently they don't like that the PCB is actually two individual PCBs in the same schematic.

**Comment by rafaeldelboni** [comment]
The unfair part is that extra fee depends on who get your pcb to analyze, it feels random, some people on reddit said that bought the same Gerber file and didn't had any extra fee. 😞 

But I still recommend their service, the quality of the product and speed is really good.
