### ISSUE TITLE
What file is used to make pcb?

### ISSUE THREAD

**Issue by ngocsangyem** [rafaeldelboni/buildlogs#6]
> As you can see, I pretty much uploaded the [latest cherry gerber file available on foostan's repository](https://github.com/foostan/crkbd/releases) in https://jlcpcb.com/ and let almost all defaults settings.

Hi @rafaeldelboni, Thank you for the build guide. It helps me a lot. But when I access the folder `https://github.com/foostan/crkbd/tree/main/corne-cherry/pcb`, I don't know which file to use to upload for the jlcpcb. Please help me point out which file it is for the left and right.

**Comment by rafaeldelboni** [comment]
Hello, I recommend you downloading the compiled Gerber from the [release pages](https://github.com/foostan/crkbd/releases).

If you willing to build the cherry V3 this is the direct [release](https://github.com/foostan/crkbd/releases/tag/corne-cherry-v3.0.1).

corne-cherry-gerber.zip has everything you need to build the keyboard without a case.

**Comment by ngocsangyem** [comment]
I got it. Thank @rafaeldelboni
