### ISSUE TITLE
Corne v3 case files

### ISSUE THREAD

**Issue by MasonJohnHawver42** [rafaeldelboni/buildlogs#8]
Hi, I have been able to find the the svg files for the corne's plates, but I don't know where to find the dimensions for them so I can cut out my own acrylic case. Could you add the dimensions and what files you used to make your own to the guide.

**Comment by rafaeldelboni** [comment]
Hey, I sent the files to my local laser cut shop, and without any questions, it sent me the cases.
I suggest opening an issue in the official keyboard repository.

https://github.com/foostan/crkbd

**Comment by rafaeldelboni** [comment]
@MasonJohnHawver42 can I close this issue?
