### ISSUE TITLE
Firmware isn't working

### ISSUE THREAD

**Issue by WritwikRay** [rafaeldelboni/buildlogs#9]
Hi! Thanks for the awesome build guide however when i flashed the pro micros the formware isn't working properly.. Both of the halves behave as master when connected separately however when i connect the TRRS cable..this isn;t working anymore...only the OLED Display on the slave side lights up and displays the Corne logo... I have tried compiling my own firmware with EE_HANDS enabled and flashing both halves separately.. the result is the correct side is recognised when connected separately however still the TRRS connection isn't working.

**Comment by WritwikRay** [comment]
Hey..thanks for the respond! I have already checked the TRRS connections..I have decided to just solder the boards together with a ribbon wire for now just to confirm that the firmware isn't responsible for this..later I will desolder these and buy a proper cable

**Comment by pwilman** [comment]
I have same similar issue. When part connected with usb works as master while the second one doesn't. Nothin on the oled and no key strokes are registered. I've check the cable and connection from board pin to board pin.

**Comment by pwilman** [comment]
OK. It works. I had to modify config.h by adding:

#define SPLIT_USB_DETECT

This changes the way how the pro micro detects the mode (if it is master or not).
